name: iOS CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build (Xcode project)
        run: |
          xcodebuild \
            -project  proximityLock/proximityLock.xcworkspace \
            -scheme proximityLock \
            -configuration Debug \
            -sdk macosx \
            CODE_SIGNING_ALLOWED=NO \
            build


